# Generated by Django 3.0.5 on 2020-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('First_name', models.CharField(max_length=30)),
                ('Hint1', models.CharField(max_length=90)),
                ('Hint2', models.CharField(max_length=90)),
                ('Secret_Friend', models.IntegerField()),
                ('Hint', models.CharField(max_length=90)),
                ('Task', models.CharField(max_length=90)),
                ('Hint_Friend', models.CharField(max_length=90)),
                ('best_M', models.CharField(max_length=30)),
                ('best_F', models.CharField(max_length=30)),
                ('submit_verfication', models.CharField(max_length=30)),
                ('Total_Gifts', models.IntegerField()),
                ('Gender', models.CharField(max_length=30)),
                ('Hint_3', models.CharField(max_length=90)),
            ],
        ),
    ]
