# Generated by Django 3.0.5 on 2020-05-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Hint_4',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
