# Generated by Django 3.0.5 on 2020-05-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20200504_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Total_Gifts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
