# Generated by Django 3.0.5 on 2020-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_employee_total_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='guess',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
