# Generated by Django 3.0.5 on 2020-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_employee_guess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='guess',
        ),
    ]
