# Generated by Django 3.0.5 on 2020-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_remove_employee_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='guess',
            field=models.CharField(default='INCORRECT', max_length=90),
            preserve_default=False,
        ),
    ]
