# Generated by Django 3.0.5 on 2020-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_employee_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Hint1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Hint2',
            field=models.CharField(max_length=500),
        ),
    ]
